# .golangci.yml - LLM Secret Interceptor Linter Configuration
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - revive
    - gosec
    - bodyclose
    - noctx
    - prealloc
